// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD38MvuROPE1jLZLmibNRgBIjde315nu0k',
    appId: '1:146338485873:web:6568b33b163db221216dd0',
    messagingSenderId: '146338485873',
    projectId: 'ditonton-3c095',
    authDomain: 'ditonton-3c095.firebaseapp.com',
    storageBucket: 'ditonton-3c095.firebasestorage.app',
    measurementId: 'G-13YJF2EJBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdi7BLF9Sxdj89Z_4ZdIAi9i_ZeWRB_wA',
    appId: '1:146338485873:android:8dd7e086abfe0741216dd0',
    messagingSenderId: '146338485873',
    projectId: 'ditonton-3c095',
    storageBucket: 'ditonton-3c095.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmxDQ6xbgONsxCx1n9LSSwSiGQ5otUkOc',
    appId: '1:146338485873:ios:cfc9257b77a04fea216dd0',
    messagingSenderId: '146338485873',
    projectId: 'ditonton-3c095',
    storageBucket: 'ditonton-3c095.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
