// Mocks generated by Mockito 5.4.4 from annotations
// in ditonton/test/presentation/pages/on_the_air_tvs_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:bloc/bloc.dart' as _i8;
import 'package:ditonton/domain/usecases/get_on_the_air_tvs.dart' as _i2;
import 'package:ditonton/domain/usecases/get_popular_tvs.dart' as _i3;
import 'package:ditonton/domain/usecases/get_top_rated_tvs.dart' as _i4;
import 'package:ditonton/presentation/bloc/tv_series/tv_list_cubit.dart'
    as _i6;
import 'package:ditonton/presentation/bloc/tv_series/tv_list_state.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetOnTheAirTvs_0 extends _i1.SmartFake
    implements _i2.GetOnTheAirTvs {
  _FakeGetOnTheAirTvs_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetPopularTvs_1 extends _i1.SmartFake implements _i3.GetPopularTvs {
  _FakeGetPopularTvs_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetTopRatedTvs_2 extends _i1.SmartFake
    implements _i4.GetTopRatedTvs {
  _FakeGetTopRatedTvs_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvListState_3 extends _i1.SmartFake implements _i5.TvListState {
  _FakeTvListState_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TvListCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvListCubit extends _i1.Mock implements _i6.TvListCubit {
  MockTvListCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetOnTheAirTvs get getOnTheAirTvs => (super.noSuchMethod(
        Invocation.getter(#getOnTheAirTvs),
        returnValue: _FakeGetOnTheAirTvs_0(
          this,
          Invocation.getter(#getOnTheAirTvs),
        ),
      ) as _i2.GetOnTheAirTvs);

  @override
  _i3.GetPopularTvs get getPopularTvs => (super.noSuchMethod(
        Invocation.getter(#getPopularTvs),
        returnValue: _FakeGetPopularTvs_1(
          this,
          Invocation.getter(#getPopularTvs),
        ),
      ) as _i3.GetPopularTvs);

  @override
  _i4.GetTopRatedTvs get getTopRatedTvs => (super.noSuchMethod(
        Invocation.getter(#getTopRatedTvs),
        returnValue: _FakeGetTopRatedTvs_2(
          this,
          Invocation.getter(#getTopRatedTvs),
        ),
      ) as _i4.GetTopRatedTvs);

  @override
  _i5.TvListState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeTvListState_3(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.TvListState);

  @override
  _i7.Stream<_i5.TvListState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i7.Stream<_i5.TvListState>.empty(),
      ) as _i7.Stream<_i5.TvListState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> fetchOnTheAirTvs() => (super.noSuchMethod(
        Invocation.method(
          #fetchOnTheAirTvs,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchPopularTvs() => (super.noSuchMethod(
        Invocation.method(
          #fetchPopularTvs,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchTopRatedTvs() => (super.noSuchMethod(
        Invocation.method(
          #fetchTopRatedTvs,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void emit(_i5.TvListState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i8.Change<_i5.TvListState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
